# Generated by Django 3.2.5 on 2022-10-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False)),
                ('name', models.CharField(max_length=255)),
                ('account_type', models.CharField(blank=True, choices=[('متاجرة', (('1', 'التأشيرات'), ('2', 'تذاكرطيران'), ('3', 'تذاكربرية'), ('4', 'تذاكربحرية'), ('5', 'شحن'), ('6', 'حجزفندقي'), ('7', 'مستندات سفر'), ('8', 'عمولات'), ('9', 'تأمين صحي'), ('10', 'رحلات'), ('11', 'تحويل عملة'), ('12', 'الاصول'), ('13', 'أرباح وخسائر'), ('14', 'رصيدمدور'), ('15', 'الاهتلاك'), ('16', 'مستحقات الموظفين'), ('17', 'التأمينات الاجتماعية'), ('18', 'المصروفات'))), ('الشركات و الزبائن', (('20', 'الزبائن'), ('21', 'شركات التأشيرات'), ('22', 'شركات نقل جوي'), ('23', 'شركات نقل بري'), ('24', 'شركات نقل بحري'), ('25', 'فنادق'), ('26', 'شركات شحن'), ('27', 'شركات تأمين صحي'))), ('حسابات الشركة', (('30', 'المالكين'), ('31', 'الموظفين'), ('32', 'الصناديق'), ('33', 'مصاريف يومية'), ('34', 'الحافلات'), ('35', 'السائقين')))], max_length=4)),
            ],
        ),
    ]
