# Generated by Django 3.2.5 on 2022-10-28 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
        ('account', '0002_initial'),
        ('coin', '0001_initial'),
        ('ked', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ked',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ked',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AddField(
            model_name='journal',
            name='account_credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_credit', to='account.account'),
        ),
        migrations.AddField(
            model_name='journal',
            name='account_dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_dept', to='account.account'),
        ),
        migrations.AddField(
            model_name='journal',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journal',
            name='coin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coin.coin'),
        ),
        migrations.AddField(
            model_name='journal',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AddField(
            model_name='journal',
            name='journal_2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ked.journal'),
        ),
        migrations.AddField(
            model_name='journal',
            name='ked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ked.ked'),
        ),
    ]
