# Generated by Django 3.2.5 on 2022-10-28 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(blank=True, max_length=100, null=True)),
                ('name_en', models.CharField(blank=True, max_length=300, null=True)),
                ('Alpha_2', models.CharField(blank=True, max_length=10, null=True)),
                ('Alpha_3', models.CharField(blank=True, max_length=10, null=True)),
                ('currency_alphabetic', models.CharField(blank=True, max_length=100, null=True)),
                ('currency_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Arabic_Formal', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, help_text='الاسم المحلي', max_length=100, null=True)),
                ('city_ascii', models.CharField(blank=True, help_text='الاسم بالانكليزية', max_length=100, null=True)),
                ('iso2', models.CharField(blank=True, max_length=100, null=True)),
                ('iso3', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='international.country')),
            ],
        ),
        migrations.CreateModel(
            name='AirPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(blank=True, max_length=10, null=True)),
                ('airport_type', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('iso_region', models.CharField(blank=True, max_length=100, null=True)),
                ('iata_code', models.CharField(blank=True, help_text='رمز الاتحاد الدولي', max_length=100, null=True)),
                ('name_ar', models.CharField(blank=True, max_length=300, null=True)),
                ('iso_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='international.country')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='international.city')),
            ],
        ),
    ]
