# Generated by Django 3.2.5 on 2022-10-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('short_title', models.CharField(blank=True, help_text='رمز مختصر ', max_length=100, null=True)),
                ('long_title', models.CharField(blank=True, help_text='الاسم كامل', max_length=300, null=True)),
                ('active', models.BooleanField(default=False, help_text='مستخدمة')),
                ('company', models.ManyToManyField(related_name='coins', to='company.Company')),
            ],
            options={
                'verbose_name_plural': 'CURRENCIES',
            },
        ),
    ]
