# Generated by Django 3.2.5 on 2022-10-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(blank=True, max_length=255, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
