# Generated by Django 3.2.5 on 2022-10-28 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0002_initial'),
        ('reservation', '0003_airlinecompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationAirline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PassengerCountAdult', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('PassengerCountChild', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('PassengerCountInfinte', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('PNR', models.CharField(blank=True, max_length=25, null=True)),
                ('departure_date', models.DateTimeField(blank=True, help_text='تاريخ المغادرة ', null=True)),
                ('flight_no', models.CharField(blank=True, max_length=25, null=True)),
                ('roundtrip', models.BooleanField(default=False, help_text='ذهاب وعودة ')),
                ('flight_type', models.CharField(choices=[('1', 'Economy Class'), ('2', 'Business Class'), ('3', 'First Class')], max_length=3)),
                ('return_date', models.DateTimeField(blank=True, help_text='تاريخ العودة ', null=True)),
                ('airline_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Airlinecompany', to='reservation.airlinecompany')),
                ('arrival', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrival', to='reservation.airport')),
                ('departure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departure', to='reservation.airport')),
                ('passport', models.ManyToManyField(to='passport.Passport')),
                ('reservationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.reservation')),
            ],
        ),
    ]
