# Generated by Django 3.2.5 on 2022-10-28 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
        ('customer', '0002_initial'),
        ('reservation', '0004_reservationairline'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationairline',
            name='pay_coin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payCoin', to='coin.coin'),
        ),
        migrations.AddField(
            model_name='reservationairline',
            name='pay_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservationairline',
            name='sell_coin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sellCoin', to='coin.coin'),
        ),
        migrations.AddField(
            model_name='reservationairline',
            name='sell_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservationairline',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Cancelled'), ('3', 'pending')], default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='reservationairline',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliersCompany', to='customer.customer'),
        ),
    ]
