# Generated by Django 3.2.5 on 2022-10-28 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_initial'),
        ('customer', '0002_initial'),
        ('coin', '0001_initial'),
        ('reservation', '0005_auto_20221028_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationairline',
            name='passport',
        ),
        migrations.CreateModel(
            name='ReservationTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PassengerCountAdult', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('PassengerCountChild', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('PassengerCountInfinte', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('departure_date', models.DateTimeField(blank=True, help_text='تاريخ المغادرة ', null=True)),
                ('roundtrip', models.BooleanField(default=False, help_text='ذهاب وعودة ')),
                ('return_date', models.DateTimeField(blank=True, help_text='تاريخ العودة ', null=True)),
                ('pay_price', models.PositiveIntegerField(default=0)),
                ('sell_price', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Cancelled'), ('3', 'pending')], default=1, max_length=2)),
                ('TripId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.trip')),
                ('arrival', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Locationto', to='trip.location')),
                ('departure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Locaionfrom', to='trip.location')),
                ('pay_coin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TransPayCoin', to='coin.coin')),
                ('reservationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.reservation')),
                ('sell_coin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TransSellCoin', to='coin.coin')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliersTransCompany', to='customer.customer')),
            ],
        ),
    ]
