# Generated by Django 3.2.5 on 2022-10-28 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_initial'),
        ('passport', '0002_initial'),
        ('coin', '0001_initial'),
        ('reservation', '0007_auto_20221028_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodstype', models.PositiveIntegerField(choices=[('1', 'Box'), ('2', 'Envelope'), ('3', 'Bag'), ('4', 'Other')], default=1)),
                ('goodscount', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('goodswight', models.FloatField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Passport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='passport.passport')),
            ],
        ),
        migrations.CreateModel(
            name='SubReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_type', models.PositiveIntegerField(choices=[('1', 'Airline'), ('2', 'Transport'), ('3', 'Farry'), ('4', 'Hotel'), ('5', 'Visa'), ('6', 'Insurance'), ('7', 'Shipping'), ('8', 'Package'), ('9', 'Document'), ('10', 'Commition')], default=1)),
                ('Itemscount', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('private_no1', models.CharField(blank=True, max_length=25, null=True)),
                ('private_no2', models.CharField(blank=True, max_length=25, null=True)),
                ('departure_date', models.DateTimeField(blank=True, help_text='تاريخ المغادرة ', null=True)),
                ('return_date', models.DateTimeField(blank=True, help_text='تاريخ العودة ', null=True)),
                ('flight_no', models.CharField(blank=True, max_length=25, null=True)),
                ('roundtrip', models.BooleanField(default=False, help_text='ذهاب وعودة ')),
                ('trip_type', models.CharField(choices=[('1', 'Economy Class'), ('2', 'Business Class'), ('3', 'First Class')], max_length=3)),
                ('pay_price', models.PositiveIntegerField(default=0)),
                ('sell_price', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Cancelled'), ('3', 'pending')], default=1, max_length=2)),
                ('ciry1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departure', to='reservation.airport')),
                ('city2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrival', to='reservation.airport')),
                ('mother_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Airlinecompany', to='reservation.mothercompany')),
                ('pay_coin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payCoin', to='coin.coin')),
                ('reservationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.reservation')),
                ('sell_coin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sellCoin', to='coin.coin')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliersCompany', to='customer.customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='reservationtransport',
            name='TripId',
        ),
        migrations.RemoveField(
            model_name='reservationtransport',
            name='arrival',
        ),
        migrations.RemoveField(
            model_name='reservationtransport',
            name='departure',
        ),
        migrations.RemoveField(
            model_name='reservationtransport',
            name='pay_coin',
        ),
        migrations.RemoveField(
            model_name='reservationtransport',
            name='reservationID',
        ),
        migrations.RemoveField(
            model_name='reservationtransport',
            name='sell_coin',
        ),
        migrations.RemoveField(
            model_name='reservationtransport',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='reservationtransport',
            name='transport_company',
        ),
        migrations.DeleteModel(
            name='ReservationAirline',
        ),
        migrations.DeleteModel(
            name='ReservationTransport',
        ),
        migrations.AddField(
            model_name='itemreservation',
            name='subreservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.subreservation'),
        ),
        migrations.AddField(
            model_name='goods',
            name='subreservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.subreservation'),
        ),
    ]
