# Generated by Django 3.2.5 on 2022-10-28 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_auto_20221028_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='titel',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='Date',
            field=models.DateTimeField(blank=True),
        ),
    ]
