# Generated by Django 3.2.5 on 2022-10-31 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_auto_20221029_0156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subreservation',
            old_name='ciry1',
            new_name='city1',
        ),
    ]
